version: '3.2'

services:
  buildpack-infra:
    image: ${GOOGLE_PROJECT_ID}-infra-prod
    build: ../../
    environment:
      - ENV=prod
      - PROJECT=${GOOGLE_PROJECT_ID}
      - REGION=${GOOGLE_COMPUTE_REGION}
      - BOTO_CONFIG=/infra/environments/prod/.boto
    volumes:
      - ~/.config:/root/.config
      - ~/.kube:/root/.kube
